objects/Blog_Suggestion__c.object
<CustomObject>
    <fields>
        <fullName>Deadline__c</fullName>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <label>Topic</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Blog Suggestion</label>
    <nameField>
        <displayFormat>BLG-{000}</displayFormat>
        <label>REFID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Blog Suggestions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BlogCalendarHandler.cls
public class BlogCalendarHandler {

    public static void addBlogTopicToCalendar(Blog_Suggestion__c bs) {
        CalendarService service = new CalendarService();
        service.useClientLogin('joshua.birk@salesforce.com','J0shua400');
        GoogleData.Calendar cal = service.getCalendarByTitle('Blog Topics');
            event newEvent = new Event(
            subject = bs.Topic__c,
            description = bs.Description__c,
            ActivityDateTime = bs.Deadline__c,
            DurationInMinutes = 60
            );
        
        xmldom.element entry = service.insertEvent( cal, newEvent );  
        entry.dumpAll();  
    }
    

    
}