objects/Car__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>Alfa Romeo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ariel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ascari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aston Martin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bentley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bristol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooke</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cadillac</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Callaway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campagna</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caterham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chevrolet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chrysler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Citroen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corvette</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daihatsu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dodge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elfin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ferrari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fiat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ford</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gumpert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Honda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hummer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyundai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invicta</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <label>Store</label>
        <referenceTo>Store__c</referenceTo>
        <relationshipLabel>Cars</relationshipLabel>
        <relationshipName>Cars</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Car</label>
    <nameField>
        <displayFormat>C-{0}</displayFormat>
        <label>Car Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Store__c.object
<CustomObject>
    <description>Represents a location of store branches withing a company.</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ManageInventoryController.cls
public class ManageInventoryController{

    List<Store__c> stores;
    
    public List<Store__c> getStores(){
        if(stores == null){
            stores = [select Id, Name, City__c, (select Id, Name, Brand__c, Model__c, VIN__c from Cars__r) from Store__c];
        }
        return stores;
    }

    public void updateCar(){
        //Get values passed from actionFunction
        String carId = ApexPages.currentPage().getParameters().get('carId');
        String storeId = ApexPages.currentPage().getParameters().get('storeId');
        
        //Create a "new" car object with Id defined and the new store Id
        Car__c car = new Car__c(Id = carId, Store__c = storeId);
        
        //Update the car record
        update car;
    
        //Then make the stores list null so that it is requeried with the new cars
        stores = null;
    } 
    
    //-- TEST METHODS --
    /*These are very bad test methods and never look at them. 
    Just threw these together so I could get the package uploaded*/
    
    static testMethod void test() { 
        //Create test date
        Store__c store = new Store__c(Name = 'my store');
        insert store;
        
        Car__c car = new Car__c();  
        insert car;
        
        Test.setCurrentPageReference(new PageReference('Page.manageInventory'));
        System.currentPageReference().getParameters().put('carId', car.id);
        System.currentPageReference().getParameters().put('storeId', store.id);
        
        ManageInventoryController controller = new ManageInventoryController();
        controller.getStores();
        controller.updateCar();
    }
}